package view;

import controller.ControladorUsuario;
import controller.ControladorVendas;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import model.Vendedor;

/**
 *
 * @author karol
 */
public class IURelatorioVendasCliente extends javax.swing.JDialog {

    /**
     * Creates new form IURelatorioVendasCliente
     */
    public IURelatorioVendasCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabelaVendaCliente.getColumnModel().getColumn(0).setPreferredWidth(150);
        tabelaVendaCliente.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaVendaCliente.getColumnModel().getColumn(2).setPreferredWidth(300);
        tabelaVendaCliente.getColumnModel().getColumn(3).setPreferredWidth(300);
        tabelaVendaCliente.getColumnModel().getColumn(4).setPreferredWidth(400);
        tabelaVendaCliente.getColumnModel().getColumn(5).setPreferredWidth(200);
        tabelaVendaCliente.getColumnModel().getColumn(6).setPreferredWidth(200);
        tabelaVendaCliente.getColumnModel().getColumn(7).setPreferredWidth(200);

        DefaultTableCellRenderer c = new DefaultTableCellRenderer();

        c.setHorizontalAlignment(SwingConstants.CENTER);

        tabelaVendaCliente.getColumnModel().getColumn(0).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(1).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(2).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(3).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(4).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(5).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(6).setCellRenderer(c);
        tabelaVendaCliente.getColumnModel().getColumn(7).setCellRenderer(c);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendaCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TextFieldCodigoCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas por Cliente");
        setPreferredSize(new java.awt.Dimension(900, 300));

        tabelaVendaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Vendedor", "Data", "Itens", "Total", "Desconto", "Pagamento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVendaCliente);

        jLabel1.setText("Código do Cliente: ");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigoClienteString = TextFieldCodigoCliente.getText();

        ControladorUsuario controllerUsuario = new ControladorUsuario();

        if (codigoClienteString.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null, "Campo vazio!", null, JOptionPane.ERROR_MESSAGE);
        } else {

            int codigoCliente = Integer.parseInt(codigoClienteString);

            Usuario usuario = controllerUsuario.getUsuarioByCodigo(codigoCliente);

            if (usuario == null || usuario instanceof Vendedor) {
                JOptionPane.showMessageDialog(
                        null, "Cliente não encontrado!", null, JOptionPane.ERROR_MESSAGE);
                TextFieldCodigoCliente.setText("");
            } else {

                ControladorVendas controllerVendas = new ControladorVendas();
                Object[][] row = controllerVendas.relatorioVendasCliente(codigoCliente);

                DefaultTableModel modelo = (DefaultTableModel) tabelaVendaCliente.getModel();

                for (int i = 0; i < row.length; i++) {
                    modelo.addRow(row[i]);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IURelatorioVendasCliente dialog = new IURelatorioVendasCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldCodigoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVendaCliente;
    // End of variables declaration//GEN-END:variables
}
