
package view;

import controller.ControladorUsuario;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 */
public class IURelatorioVendedorMes extends javax.swing.JDialog {

    /**
     * Creates new form IURelatorioVendedorMes
     */
    public IURelatorioVendedorMes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tabelaVendedorMes.getColumnModel().getColumn(0).setPreferredWidth(150);
        tabelaVendedorMes.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaVendedorMes.getColumnModel().getColumn(2).setPreferredWidth(300);
        tabelaVendedorMes.getColumnModel().getColumn(3).setPreferredWidth(300);
        tabelaVendedorMes.getColumnModel().getColumn(4).setPreferredWidth(300);
        tabelaVendedorMes.getColumnModel().getColumn(5).setPreferredWidth(400);
        tabelaVendedorMes.getColumnModel().getColumn(6).setPreferredWidth(400);
        tabelaVendedorMes.getColumnModel().getColumn(7).setPreferredWidth(400);
        tabelaVendedorMes.getColumnModel().getColumn(8).setPreferredWidth(200);
        tabelaVendedorMes.getColumnModel().getColumn(9).setPreferredWidth(200);
        tabelaVendedorMes.getColumnModel().getColumn(10).setPreferredWidth(300);
        tabelaVendedorMes.getColumnModel().getColumn(11).setPreferredWidth(150);
         
        DefaultTableCellRenderer c = new DefaultTableCellRenderer();  
 
        c.setHorizontalAlignment(SwingConstants.CENTER);
        
        tabelaVendedorMes.getColumnModel().getColumn(0).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(1).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(2).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(3).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(4).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(5).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(6).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(7).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(8).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(9).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(10).setCellRenderer(c);
        tabelaVendedorMes.getColumnModel().getColumn(11).setCellRenderer(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendedorMes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        buttonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendedor do Mês");

        tabelaVendedorMes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "RG", "Nascimento", "Endereço", "CEP", "Email", "Salário", "PIS", "Admissão", "Vendas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaVendedorMes);

        jLabel1.setText("Funcionário do mês:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        buttonBuscar.setBackground(new java.awt.Color(60, 121, 201));
        buttonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        buttonBuscar.setText("Buscar");
        buttonBuscar.setBorderPainted(false);
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        String mes = jComboBoxMes.getSelectedItem().toString();
        
        ControladorUsuario controller = new ControladorUsuario();
        Object [][] row = controller.relatorioVendedorMes(Integer.parseInt(mes));
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaVendedorMes.getModel();
        
        for(int i = 0; i < modelo.getRowCount(); i++){
            modelo.removeRow(i);
        }
        
        for(int i = 0; i < row.length; i++){
            modelo.addRow(row[i]);
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendedorMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendedorMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendedorMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IURelatorioVendedorMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IURelatorioVendedorMes dialog = new IURelatorioVendedorMes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVendedorMes;
    // End of variables declaration//GEN-END:variables
}
