/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ControladorProduto;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karol
 */
public class IURelatorioProdutosOrdenados extends javax.swing.JDialog {

    /**
     * Creates new form IURelatorioProdutosOrdenados
     */
    public IURelatorioProdutosOrdenados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        tabelaProdutosOrdenados.getColumnModel().getColumn(0).setPreferredWidth(150);
        tabelaProdutosOrdenados.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaProdutosOrdenados.getColumnModel().getColumn(2).setPreferredWidth(400);
        tabelaProdutosOrdenados.getColumnModel().getColumn(3).setPreferredWidth(200);
        tabelaProdutosOrdenados.getColumnModel().getColumn(4).setPreferredWidth(150);
        tabelaProdutosOrdenados.getColumnModel().getColumn(5).setPreferredWidth(200);
        tabelaProdutosOrdenados.getColumnModel().getColumn(6).setPreferredWidth(200);

        DefaultTableCellRenderer c = new DefaultTableCellRenderer();

        c.setHorizontalAlignment(SwingConstants.CENTER);

        tabelaProdutosOrdenados.getColumnModel().getColumn(0).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(1).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(2).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(3).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(4).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(5).setCellRenderer(c);
        tabelaProdutosOrdenados.getColumnModel().getColumn(6).setCellRenderer(c);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutosOrdenados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        comboBoxAlgoritmo = new javax.swing.JComboBox<>();
        buttonOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos Ordenados por Valor");
        setPreferredSize(new java.awt.Dimension(700, 300));

        tabelaProdutosOrdenados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Descrição", "Fabricação", "Valor", "Fornecedor", "Disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutosOrdenados);

        jLabel1.setText("Algoritmo: ");

        comboBoxAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quick Sort", "Insertion Sort" }));

        buttonOrdenar.setText("Ordenar");
        buttonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOrdenarActionPerformed
        String strategy = comboBoxAlgoritmo.getSelectedItem().toString();
        
        System.out.println(strategy.getClass());

        ControladorProduto controller = new ControladorProduto();
        Object[][] row = controller.getProdutosOrdenados(strategy);

        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutosOrdenados.getModel();

        for (int i = 0; i < row.length; i++) {
            modelo.addRow(row[i]);
        }
    }//GEN-LAST:event_buttonOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IURelatorioProdutosOrdenados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IURelatorioProdutosOrdenados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IURelatorioProdutosOrdenados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IURelatorioProdutosOrdenados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IURelatorioProdutosOrdenados dialog = new IURelatorioProdutosOrdenados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOrdenar;
    private javax.swing.JComboBox<String> comboBoxAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutosOrdenados;
    // End of variables declaration//GEN-END:variables
}
